import {
  DailyMission,
  WeeklyMission,
  GamificationAchievement,
  SeasonalEvent,
  LeaderboardUser,
} from './xp-engine';

export const MOCK_DAILY_MISSIONS: DailyMission[] = [
  {
    id: 'dm-1',
    title: 'Complete 1 Proctored Micro-Assessment',
    category: 'Assessment',
    targetCount: 1,
    currentCount: 1,
    xpReward: 50,
    isCompleted: true,
  },
  {
    id: 'dm-2',
    title: 'Push Verified GitHub Commit with Tests',
    category: 'GitHub',
    targetCount: 1,
    currentCount: 1,
    xpReward: 30,
    isCompleted: true,
  },
  {
    id: 'dm-3',
    title: 'Update Project Architecture Documentation',
    category: 'Project',
    targetCount: 1,
    currentCount: 0,
    xpReward: 40,
    isCompleted: false,
  },
  {
    id: 'dm-4',
    title: 'Join Community Technical Q&A Discussion',
    category: 'Community',
    targetCount: 1,
    currentCount: 1,
    xpReward: 25,
    isCompleted: true,
  },
  {
    id: 'dm-5',
    title: 'Complete 15-min AI Revision Task',
    category: 'Learning',
    targetCount: 1,
    currentCount: 0,
    xpReward: 35,
    isCompleted: false,
  },
];

export const MOCK_WEEKLY_MISSIONS: WeeklyMission[] = [
  {
    id: 'wm-1',
    title: 'Finish 1 Major Project Milestone Deployment',
    category: 'Project',
    targetCount: 1,
    currentCount: 1,
    xpReward: 250,
    isCompleted: true,
  },
  {
    id: 'wm-2',
    title: 'Attend Faculty Live Smart Room Workshop',
    category: 'Workshop',
    targetCount: 1,
    currentCount: 1,
    xpReward: 150,
    isCompleted: true,
  },
  {
    id: 'wm-3',
    title: 'Pass 1 Advanced Benchmark Assessment',
    category: 'Assessment',
    targetCount: 1,
    currentCount: 0,
    xpReward: 200,
    isCompleted: false,
  },
  {
    id: 'wm-4',
    title: 'Contribute 2 Peer Code Reviews to Community',
    category: 'Community',
    targetCount: 2,
    currentCount: 1,
    xpReward: 100,
    isCompleted: false,
  },
];

export const MOCK_ACHIEVEMENTS: GamificationAchievement[] = [
  {
    id: 'ach-1',
    title: 'First Project Unlocked',
    description: 'Create & deploy your first verified software repository.',
    iconName: 'FolderGit2',
    category: 'Milestone',
    unlockedAt: '2025-08-20',
    isUnlocked: true,
    xpValue: 100,
  },
  {
    id: 'ach-2',
    title: 'First Assessment Mastered',
    description: 'Pass your initial diagnostic skill assessment test.',
    iconName: 'Award',
    category: 'Milestone',
    unlockedAt: '2025-08-15',
    isUnlocked: true,
    xpValue: 50,
  },
  {
    id: 'ach-3',
    title: 'GitHub Connected & Verified',
    description: 'Link your GitHub account & sync commit activity log.',
    iconName: 'GitCommit',
    category: 'Milestone',
    unlockedAt: '2025-08-15',
    isUnlocked: true,
    xpValue: 50,
  },
  {
    id: 'ach-4',
    title: '7-Day Building Streak',
    description: 'Maintain verified building & learning activity for 7 consecutive days.',
    iconName: 'Zap',
    category: 'Streak',
    unlockedAt: '2025-09-01',
    isUnlocked: true,
    xpValue: 150,
  },
  {
    id: 'ach-5',
    title: '30-Day Master Streak',
    description: 'Maintain verified building & learning activity for 30 consecutive days.',
    iconName: 'Flame',
    category: 'Streak',
    unlockedAt: '2025-09-24',
    isUnlocked: true,
    xpValue: 500,
  },
  {
    id: 'ach-6',
    title: 'Community Technical Mentor',
    description: 'Provide 10+ verified peer code reviews and answer doubts.',
    iconName: 'Users',
    category: 'Community',
    unlockedAt: '2025-09-15',
    isUnlocked: true,
    xpValue: 300,
  },
  {
    id: 'ach-7',
    title: 'Top Builder Leaderboard',
    description: 'Rank among top 10 verified builders across institution.',
    iconName: 'Trophy',
    category: 'Career',
    unlockedAt: '2025-09-20',
    isUnlocked: true,
    xpValue: 400,
  },
  {
    id: 'ach-8',
    title: 'Industry Ready Certified',
    description: 'Achieve Level 7 Builder status with 3500+ verified XP.',
    iconName: 'ShieldCheck',
    category: 'Career',
    unlockedAt: '2026-09-26',
    isUnlocked: true,
    xpValue: 1000,
  },
];

export const MOCK_SEASONAL_EVENTS: SeasonalEvent[] = [
  {
    id: 'ev-1',
    title: 'SIH 2026 AI & Systems Hackathon',
    type: 'Hackathon',
    duration: 'Sept 26 - Oct 02, 2026',
    startDate: 'Sept 26, 2026',
    prizePoolXP: 5000,
    registeredCount: 142,
    status: 'Active',
    description: 'Build edge AI telemetry pipelines & cloud microservices for real-world industry challenges.',
  },
  {
    id: 'ev-2',
    title: 'Spring Boot Microservices Build Sprint',
    type: 'Build Sprint',
    duration: 'Oct 05 - Oct 12, 2026',
    startDate: 'Oct 05, 2026',
    prizePoolXP: 3000,
    registeredCount: 98,
    status: 'Upcoming',
    description: '7-day intensive sprint implementing Resilience4j circuit breakers & Kafka telemetry.',
  },
  {
    id: 'ev-3',
    title: 'National Innovation Week Challenge',
    type: 'Innovation Week',
    duration: 'Nov 01 - Nov 07, 2026',
    startDate: 'Nov 01, 2026',
    prizePoolXP: 10000,
    registeredCount: 310,
    status: 'Upcoming',
    description: 'University-wide innovation showcase presented directly to enterprise recruiters.',
  },
];

export const MOCK_LEADERBOARD_USERS: LeaderboardUser[] = [
  {
    id: 'lb-1',
    rank: 1,
    name: 'Manutej Reddy',
    rollNumber: '22HT1A0501',
    department: 'Computer Science & Engineering',
    verifiedXP: 4250,
    level: 7,
    levelTitle: 'Industry Ready',
    githubProjectsCount: 8,
  },
  {
    id: 'lb-2',
    rank: 2,
    name: 'Priya Sharma',
    rollNumber: '22HT1A0514',
    department: 'Computer Science & Engineering',
    verifiedXP: 3890,
    level: 7,
    levelTitle: 'Industry Ready',
    githubProjectsCount: 6,
  },
  {
    id: 'lb-3',
    rank: 3,
    name: 'Aarav Patel',
    rollNumber: '22HT1A0545',
    department: 'Artificial Intelligence',
    verifiedXP: 3420,
    level: 6,
    levelTitle: 'Master Builder',
    githubProjectsCount: 5,
  },
  {
    id: 'lb-4',
    rank: 4,
    name: 'Ananya Verma',
    rollNumber: '22HT1A0560',
    department: 'Computer Science & Engineering',
    verifiedXP: 3100,
    level: 6,
    levelTitle: 'Master Builder',
    githubProjectsCount: 5,
  },
  {
    id: 'lb-5',
    rank: 5,
    name: 'Karthik Raja',
    rollNumber: '22HT1A0532',
    department: 'Information Technology',
    verifiedXP: 2750,
    level: 6,
    levelTitle: 'Master Builder',
    githubProjectsCount: 4,
  },
];
