import { OpportunityItem, ApplicationRecord, RecruiterBuilderCard } from './types';

export const MOCK_OPPORTUNITIES: OpportunityItem[] = [
  {
    id: 'opp-1',
    title: 'Google STEP Software Engineering Intern 2026',
    organization: 'Google',
    logoUrl: 'https://images.unsplash.com/photo-1573804633927-bf7713b2968a?w=120&auto=format&fit=crop&q=60',
    type: 'Internships',
    description: '12-week summer internship program for undergraduate computer science students. Focus on algorithm development, scalable system infrastructure, and production software engineering.',
    eligibility: '3rd Year B.Tech CSE / IT / ECE students with CGPA > 8.0',
    skillsRequired: ['Java', 'Data Structures & Algorithms', 'Problem Solving', 'REST APIs', 'Git'],
    deadline: 'Oct 15, 2026',
    location: 'Bengaluru / Hyderabad (Hybrid)',
    compensation: '₹85,000 / month',
    difficultyLevel: 'Advanced',
    applicationUrl: 'https://careers.google.com/jobs/step-intern-2026',
    postedDate: 'Sept 20, 2026',
    match: {
      overallMatchScore: 87,
      readinessScore: 82,
      skillAlignmentPct: 85,
      projectAlignmentPct: 90,
      githubAlignmentPct: 88,
      assessmentAlignmentPct: 84,
      builderScoreAlignmentPct: 92,
      missingSkills: ['DSA Graph Algorithms', 'Advanced Java Collections', 'Concurrency'],
      matchedSkills: ['Java Core', 'REST APIs', 'Git Commit Velocity', 'System Architecture'],
      recommendedProjectsToBuild: ['High-Throughput Redis Rate Limiter', 'Multi-Threaded Key-Value Store'],
      recommendedAssessmentsToTake: ['Data Structures & Algorithms Hard Eval', 'Java Concurrency Exam'],
      expectedReadinessGain: '+11% Match Gain in 2 Weeks',
    },
    saved: true,
    applied: true,
    applicationStage: 'Shortlisted',
    appliedDate: 'Sept 22, 2026',
  },
  {
    id: 'opp-2',
    title: 'Backend Software Engineering Intern (Payments API)',
    organization: 'Razorpay',
    logoUrl: 'https://images.unsplash.com/photo-1556742049-0a67daf64f42?w=120&auto=format&fit=crop&q=60',
    type: 'Internships',
    description: 'Work alongside Razorpay core payments team building resilient Java Spring Boot microservices, high-load payment gateways, and Redis caching infrastructure.',
    eligibility: 'Pre-final or Final Year Students with solid Java / Spring Boot experience',
    skillsRequired: ['Java 21', 'Spring Boot', 'PostgreSQL', 'Docker', 'REST APIs'],
    deadline: 'Oct 05, 2026',
    location: 'Bengaluru / Remote',
    compensation: '₹60,000 / month',
    difficultyLevel: 'Industry-Level',
    applicationUrl: 'https://razorpay.com/careers/backend-intern',
    postedDate: 'Sept 22, 2026',
    match: {
      overallMatchScore: 92,
      readinessScore: 90,
      skillAlignmentPct: 94,
      projectAlignmentPct: 92,
      githubAlignmentPct: 90,
      assessmentAlignmentPct: 88,
      builderScoreAlignmentPct: 95,
      missingSkills: ['Spring Security JWT filter optimization'],
      matchedSkills: ['Java 21', 'Spring Boot', 'REST APIs', 'PostgreSQL', 'Docker Compose'],
      recommendedProjectsToBuild: ['Dockerized Multi-Container Microservices Cluster'],
      recommendedAssessmentsToTake: ['Spring Boot Core REST Architecture Quiz'],
      expectedReadinessGain: '+6% Match Gain to reach 98% Match',
    },
    saved: true,
    applied: true,
    applicationStage: 'Interview',
    appliedDate: 'Sept 24, 2026',
  },
  {
    id: 'opp-3',
    title: 'Junior Systems & Cloud DevOps Trainee',
    organization: 'Swiggy',
    type: 'Jobs',
    description: 'Join Swiggy Infrastructure team automating Kubernetes deployment pipelines, Prometheus telemetry monitoring, and zero-downtime canary releases.',
    eligibility: 'Final Year B.Tech CSE / IT graduating in 2026',
    skillsRequired: ['Docker', 'Kubernetes', 'Terraform', 'Prometheus', 'Linux Shell'],
    deadline: 'Nov 01, 2026',
    location: 'Bengaluru',
    compensation: '₹14 LPA - ₹18 LPA',
    difficultyLevel: 'Advanced',
    applicationUrl: 'https://swiggy.com/careers/junior-devops',
    postedDate: 'Sept 24, 2026',
    match: {
      overallMatchScore: 85,
      readinessScore: 80,
      skillAlignmentPct: 82,
      projectAlignmentPct: 88,
      githubAlignmentPct: 85,
      assessmentAlignmentPct: 80,
      builderScoreAlignmentPct: 90,
      missingSkills: ['Kubernetes Helm Charts', 'Terraform AWS Modules'],
      matchedSkills: ['Docker Containerization', 'CI/CD Pipelines', 'Linux Kernel Basics'],
      recommendedProjectsToBuild: ['Zero-Downtime Kubernetes GitOps Pipeline'],
      recommendedAssessmentsToTake: ['Docker Containerization & CLI Practical Lab'],
      expectedReadinessGain: '+12% Match Gain in 3 Weeks',
    },
    saved: false,
    applied: false,
  },
  {
    id: 'opp-4',
    title: 'Global Autonomous AI Agent Challenge 2026',
    organization: 'Google Cloud AI',
    type: 'Hackathons',
    description: 'Build production-grade cyclic AI graphs using LangGraph, Python FastAPI, and pgvector vector search to automate complex developer workflows.',
    eligibility: 'Open to all college students & developer builders',
    skillsRequired: ['Python', 'LangChain / LangGraph', 'FastAPI', 'pgvector', 'Docker'],
    deadline: 'Oct 20, 2026',
    location: 'Global Virtual',
    compensation: '$15,000 Total Prize Pool + Google Cloud Credits',
    difficultyLevel: 'Industry-Level',
    applicationUrl: 'https://hackathons.google.dev/ai-agent-2026',
    postedDate: 'Sept 18, 2026',
    match: {
      overallMatchScore: 89,
      readinessScore: 86,
      skillAlignmentPct: 88,
      projectAlignmentPct: 90,
      githubAlignmentPct: 89,
      assessmentAlignmentPct: 86,
      builderScoreAlignmentPct: 92,
      missingSkills: ['LangGraph Cyclic State Machine', 'BM25 + Dense Reranking'],
      matchedSkills: ['Python', 'FastAPI', 'pgvector Embeddings', 'Docker'],
      recommendedProjectsToBuild: ['Autonomous Multi-Agent AI Workflow Engine'],
      recommendedAssessmentsToTake: ['Python & FastAPI Microservices Eval'],
      expectedReadinessGain: '+8% Match Gain in 1 Week',
    },
    saved: true,
    applied: true,
    applicationStage: 'Applied',
    appliedDate: 'Sept 21, 2026',
  },
  {
    id: 'opp-5',
    title: 'Open Source Fellow - Distributed Systems Core',
    organization: 'CNCF (Cloud Native Computing Foundation)',
    type: 'Open Source Programs',
    description: '3-month paid open source fellowship contributing directly to CNCF ecosystem projects (Kubernetes, Helm, Jaeger telemetry).',
    eligibility: 'Active GitHub contributors with verified open source PRs',
    skillsRequired: ['Go / Java', 'Distributed Systems', 'Git PR Workflow', 'Docker'],
    deadline: 'Oct 30, 2026',
    location: 'Remote',
    compensation: '$6,000 Stipend',
    difficultyLevel: 'Industry-Level',
    applicationUrl: 'https://cncf.io/fellowships/2026',
    postedDate: 'Sept 15, 2026',
    match: {
      overallMatchScore: 88,
      readinessScore: 84,
      skillAlignmentPct: 86,
      projectAlignmentPct: 91,
      githubAlignmentPct: 94,
      assessmentAlignmentPct: 82,
      builderScoreAlignmentPct: 90,
      missingSkills: ['Go Concurrency Routines', 'gRPC Protocol Buffers'],
      matchedSkills: ['Distributed Systems', 'Git Velocity', 'Docker', 'System Design'],
      recommendedProjectsToBuild: ['High-Throughput Redis Rate Limiter'],
      recommendedAssessmentsToTake: ['System Design & Scalability Diagnostic'],
      expectedReadinessGain: '+9% Match Gain in 2 Weeks',
    },
    saved: true,
    applied: false,
  },
];

export const MOCK_APPLICATIONS: ApplicationRecord[] = [
  {
    id: 'app-1',
    opportunityId: 'opp-1',
    title: 'Google STEP Software Engineering Intern 2026',
    organization: 'Google',
    stage: 'Shortlisted',
    appliedDate: 'Sept 22, 2026',
    lastUpdatedDate: 'Sept 25, 2026',
    nextStep: 'Technical Telephonic Round scheduled on Oct 02',
    notes: 'Passed resume screening & Builder Score alignment threshold.',
  },
  {
    id: 'app-2',
    opportunityId: 'opp-2',
    title: 'Backend Software Engineering Intern (Payments API)',
    organization: 'Razorpay',
    stage: 'Interview',
    appliedDate: 'Sept 24, 2026',
    lastUpdatedDate: 'Sept 26, 2026',
    nextStep: 'Live Coding & System Architecture Round',
    notes: 'Match score 92% highlighted during recruiter review.',
  },
  {
    id: 'app-3',
    opportunityId: 'opp-4',
    title: 'Global Autonomous AI Agent Challenge 2026',
    organization: 'Google Cloud AI',
    stage: 'Applied',
    appliedDate: 'Sept 21, 2026',
    lastUpdatedDate: 'Sept 21, 2026',
    nextStep: 'Awaiting Code Repository Submission',
  },
];

export const MOCK_RECRUITER_BUILDERS: RecruiterBuilderCard[] = [
  {
    id: 'rec-b1',
    name: 'Pratik Badiger',
    avatar: 'https://github.com/pratikbadiger069.png',
    role: 'Backend & Systems Architect Target',
    builderScore: 885,
    verifiedProjectsCount: 3,
    commitsCount: 142,
    passedAssessmentsCount: 4,
    communityContributionsCount: 24,
    skills: ['Java 21', 'Spring Boot', 'TypeScript', 'Docker', 'System Design', 'PostgreSQL'],
    matchScoreForRole: 94,
    status: 'Available',
  },
  {
    id: 'rec-b2',
    name: 'Ananya Sharma',
    avatar: '',
    role: 'Frontend & UI/UX Specialist',
    builderScore: 850,
    verifiedProjectsCount: 4,
    commitsCount: 98,
    passedAssessmentsCount: 3,
    communityContributionsCount: 18,
    skills: ['React', 'TypeScript', 'TailwindCSS', 'Framer Motion', 'WebSockets'],
    matchScoreForRole: 91,
    status: 'Available',
  },
  {
    id: 'rec-b3',
    name: 'Rohan Verma',
    avatar: '',
    role: 'DevOps & Cloud Engineer',
    builderScore: 820,
    verifiedProjectsCount: 2,
    commitsCount: 84,
    passedAssessmentsCount: 3,
    communityContributionsCount: 12,
    skills: ['Docker', 'Kubernetes', 'Terraform', 'Prometheus', 'AWS'],
    matchScoreForRole: 88,
    status: 'In Discussions',
  },
];
