import { ProjectHubItem } from './types';

export const MOCK_PROJECTS: ProjectHubItem[] = [
  {
    id: 'proj-sb-1',
    title: 'SkillBridge Autonomous Mentorship Engine & Telemetry OS',
    description: 'Multi-tenant AI career mentorship platform with real-time code evaluation, GitHub webhook telemetry sync, and automated skill-gap diagnostics.',
    type: 'Team',
    techStack: ['Next.js 16', 'TypeScript', 'TailwindCSS', 'Zustand', 'Prisma', 'PostgreSQL', 'Docker'],
    difficulty: 'Industry-Level',
    status: 'Production Ready',
    progressPercentage: 96,
    repositoryUrl: 'https://github.com/pratikbadiger069/Skill-Bridge',
    demoUrl: 'https://skillbridge.dev',
    documentationUrl: 'https://github.com/pratikbadiger069/Skill-Bridge#readme',
    teamMembers: [
      {
        id: 'user-1',
        name: 'Pratik Badiger',
        avatar: 'https://github.com/pratikbadiger069.png',
        role: 'Lead Architect',
        commitsCount: 142,
        linesAdded: 18400,
        linesDeleted: 2100,
        githubUsername: 'pratikbadiger069',
      },
      {
        id: 'user-2',
        name: 'Ananya Sharma',
        avatar: '',
        role: 'Frontend Engineer',
        commitsCount: 38,
        linesAdded: 4200,
        linesDeleted: 850,
        githubUsername: 'anasharma',
      },
      {
        id: 'user-3',
        name: 'Rohan Verma',
        avatar: '',
        role: 'DevOps Specialist',
        commitsCount: 24,
        linesAdded: 1900,
        linesDeleted: 340,
        githubUsername: 'rohanv',
      },
    ],
    tasks: [
      { id: 't-1', title: 'Implement GitHub Webhook Telemetry Sync', assignee: 'Pratik Badiger', status: 'Done', priority: 'High', dueDate: 'Yesterday' },
      { id: 't-2', title: 'Optimize Next.js Static & Dynamic Build Pipeline', assignee: 'Rohan Verma', status: 'Done', priority: 'High', dueDate: 'Today' },
      { id: 't-3', title: 'Add STAR Method Behavioral Interview Rubric', assignee: 'Ananya Sharma', status: 'Code Review', priority: 'Medium', dueDate: 'Tomorrow' },
      { id: 't-4', title: 'Integrate PostgreSQL Connection Pooling', assignee: 'Rohan Verma', status: 'To Do', priority: 'Low', dueDate: 'In 3 days' },
    ],
    issues: [
      { id: 'i-1', issueNumber: 42, title: 'Refactor Spring Security JWT Authentication Filter', author: 'pratikbadiger069', status: 'Closed', createdAt: '3 days ago', labels: ['security', 'enhancement'] },
      { id: 'i-2', issueNumber: 45, title: 'Add Dockerfile Multi-Stage Build Optimization', author: 'rohanv', status: 'Closed', createdAt: '2 days ago', labels: ['devops', 'performance'] },
      { id: 'i-3', issueNumber: 48, title: 'Mobile Responsiveness on Interactive Mentor Drawer', author: 'anasharma', status: 'Open', createdAt: '1 day ago', labels: ['ui', 'bug'] },
    ],
    milestones: [
      { id: 'm-1', title: 'Phase 1: Core System Architecture & UI Design', dueDate: 'Sept 15, 2026', completed: true, tasksCount: 12, completedTasksCount: 12 },
      { id: 'm-2', title: 'Phase 2: AI Copilot & Telemetry Integration', dueDate: 'Sept 22, 2026', completed: true, tasksCount: 16, completedTasksCount: 16 },
      { id: 'm-3', title: 'Phase 3: Production Deployment & Faculty Audit', dueDate: 'Sept 30, 2026', completed: false, tasksCount: 10, completedTasksCount: 8 },
    ],
    verification: {
      codeQualityScore: 94,
      documentationScore: 90,
      githubActivityScore: 96,
      deploymentStatus: 'Live Production',
      deploymentUrl: 'https://skillbridge.dev',
      peerReviewsCount: 8,
      facultyReviewer: 'Dr. Evelyn Vance (HOD CSE)',
      facultyGrade: 'A+ Verified',
      verifiedAt: 'Sept 25, 2026',
    },
    impactScore: {
      overall: 94,
      complexity: 19,
      execution: 19,
      activity: 15,
      users: 14,
      documentation: 14,
      consistency: 13,
    },
    chatMessages: [
      { id: 'cm-1', sender: 'Pratik Badiger', text: 'Hey team, I updated the Career Copilot 7-telemetry data streams!', timestamp: '10:14 AM' },
      { id: 'cm-2', sender: 'Rohan Verma', text: 'Awesome! Docker Compose containerization script is also verified.', timestamp: '10:20 AM' },
      { id: 'cm-3', sender: 'Dr. Evelyn Vance', text: '📢 Faculty Audit Complete: Excellent code structure and architecture documentation.', timestamp: '11:00 AM', isAnnouncement: true },
    ],
    screenshots: [
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=60',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=60',
    ],
    starsCount: 48,
    viewsCount: 1240,
    forksCount: 12,
    createdAt: 'Aug 20, 2026',
    updatedAt: 'Just Now',
  },
  {
    id: 'proj-sb-2',
    title: 'Distributed Event-Driven Order Processing Microservice',
    description: 'High-throughput e-commerce microservices cluster built with Java Spring Boot, Apache Kafka event streams, Redis caching, and PostgreSQL sharding.',
    type: 'Industry Challenge',
    techStack: ['Java 21', 'Spring Boot 3', 'Apache Kafka', 'Redis', 'PostgreSQL', 'Docker'],
    difficulty: 'Industry-Level',
    status: 'Verified',
    progressPercentage: 88,
    repositoryUrl: 'https://github.com/pratikbadiger069/spring-boot-order-service',
    demoUrl: 'https://orders-api.skillbridge.dev',
    documentationUrl: 'https://github.com/pratikbadiger069/spring-boot-order-service#architecture',
    teamMembers: [
      {
        id: 'user-1',
        name: 'Pratik Badiger',
        avatar: 'https://github.com/pratikbadiger069.png',
        role: 'Backend Developer',
        commitsCount: 84,
        linesAdded: 9200,
        linesDeleted: 1100,
        githubUsername: 'pratikbadiger069',
      },
    ],
    tasks: [
      { id: 't-21', title: 'Implement Token Bucket Rate Limiter Filter', assignee: 'Pratik Badiger', status: 'Done', priority: 'High' },
      { id: 't-22', title: 'Configure Kafka Dead Letter Queue (DLQ)', assignee: 'Pratik Badiger', status: 'Done', priority: 'High' },
    ],
    issues: [
      { id: 'i-21', issueNumber: 12, title: 'Fix Kafka Consumer Rebalance Timeout', author: 'pratikbadiger069', status: 'Closed', createdAt: '4 days ago', labels: ['kafka'] },
    ],
    milestones: [
      { id: 'm-21', title: 'Spring Boot REST Controllers & JPA Mapping', dueDate: 'Sept 10, 2026', completed: true, tasksCount: 8, completedTasksCount: 8 },
      { id: 'm-22', title: 'Kafka Messaging & Docker Compose Stack', dueDate: 'Sept 20, 2026', completed: true, tasksCount: 10, completedTasksCount: 10 },
    ],
    verification: {
      codeQualityScore: 92,
      documentationScore: 88,
      githubActivityScore: 90,
      deploymentStatus: 'Live Production',
      deploymentUrl: 'https://orders-api.skillbridge.dev',
      peerReviewsCount: 5,
      facultyReviewer: 'Prof. Rajesh Kumar',
      facultyGrade: 'Grade A',
      verifiedAt: 'Sept 22, 2026',
    },
    impactScore: {
      overall: 89,
      complexity: 18,
      execution: 18,
      activity: 14,
      users: 13,
      documentation: 13,
      consistency: 13,
    },
    chatMessages: [],
    screenshots: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=60',
    ],
    starsCount: 32,
    viewsCount: 890,
    forksCount: 6,
    createdAt: 'Sept 01, 2026',
    updatedAt: '2 days ago',
  },
  {
    id: 'proj-sb-3',
    title: 'Autonomous Multi-Agent AI Workflow Engine',
    description: 'Stateful cyclic AI graph engine with LangGraph, hybrid vector search (pgvector), and automated tool calling for developer automation.',
    type: 'Research',
    techStack: ['Python', 'FastAPI', 'LangChain', 'pgvector', 'React', 'Docker'],
    difficulty: 'Advanced',
    status: 'In Development',
    progressPercentage: 72,
    repositoryUrl: 'https://github.com/pratikbadiger069/agentic-ai-workflow',
    demoUrl: 'https://agentic-ai.skillbridge.dev',
    documentationUrl: 'https://github.com/pratikbadiger069/agentic-ai-workflow#docs',
    teamMembers: [
      {
        id: 'user-1',
        name: 'Pratik Badiger',
        avatar: 'https://github.com/pratikbadiger069.png',
        role: 'AI Engineer',
        commitsCount: 62,
        linesAdded: 6800,
        linesDeleted: 750,
        githubUsername: 'pratikbadiger069',
      },
    ],
    tasks: [
      { id: 't-31', title: 'Implement Hybrid BM25 + Dense Reranker', assignee: 'Pratik Badiger', status: 'In Progress', priority: 'High' },
    ],
    issues: [],
    milestones: [
      { id: 'm-31', title: 'LangGraph State Machine Setup', dueDate: 'Sept 28, 2026', completed: true, tasksCount: 6, completedTasksCount: 6 },
    ],
    verification: {
      codeQualityScore: 88,
      documentationScore: 84,
      githubActivityScore: 89,
      deploymentStatus: 'Staging',
      deploymentUrl: 'https://agentic-ai.skillbridge.dev',
      peerReviewsCount: 3,
      facultyReviewer: 'Dr. Evelyn Vance',
      facultyGrade: 'Under Review',
    },
    impactScore: {
      overall: 84,
      complexity: 17,
      execution: 16,
      activity: 14,
      users: 12,
      documentation: 13,
      consistency: 12,
    },
    chatMessages: [],
    screenshots: [
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=60',
    ],
    starsCount: 28,
    viewsCount: 640,
    forksCount: 4,
    createdAt: 'Sept 10, 2026',
    updatedAt: '3 hours ago',
  },
  {
    id: 'proj-sb-4',
    title: 'Zero-Downtime Kubernetes GitOps CI/CD Pipeline',
    description: 'ArgoCD deployment pipeline with automated rollback triggers on Prometheus error-budget spikes and Terraform AWS infrastructure provisioning.',
    type: 'Hackathon',
    techStack: ['Kubernetes', 'Terraform', 'Helm', 'ArgoCD', 'Prometheus', 'AWS'],
    difficulty: 'Advanced',
    status: 'Verified',
    progressPercentage: 100,
    repositoryUrl: 'https://github.com/pratikbadiger069/k8s-gitops-pipeline',
    demoUrl: 'https://grafana.skillbridge.dev',
    teamMembers: [
      {
        id: 'user-1',
        name: 'Pratik Badiger',
        avatar: 'https://github.com/pratikbadiger069.png',
        role: 'DevOps Specialist',
        commitsCount: 45,
        linesAdded: 3800,
        linesDeleted: 400,
        githubUsername: 'pratikbadiger069',
      },
    ],
    tasks: [],
    issues: [],
    milestones: [],
    verification: {
      codeQualityScore: 95,
      documentationScore: 92,
      githubActivityScore: 94,
      deploymentStatus: 'Live Production',
      deploymentUrl: 'https://grafana.skillbridge.dev',
      peerReviewsCount: 6,
      facultyReviewer: 'Prof. Rajesh Kumar',
      facultyGrade: 'Grade A+ (Hackathon Winner)',
      verifiedAt: 'Sept 18, 2026',
    },
    impactScore: {
      overall: 91,
      complexity: 19,
      execution: 18,
      activity: 14,
      users: 13,
      documentation: 14,
      consistency: 13,
    },
    chatMessages: [],
    screenshots: [
      'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&auto=format&fit=crop&q=60',
    ],
    starsCount: 56,
    viewsCount: 1580,
    forksCount: 14,
    createdAt: 'Sept 05, 2026',
    updatedAt: '1 week ago',
  },
];
