import {
  FacultyClass,
  StudentRecord,
  AssignmentItem,
  StudentSubmission,
  UpcomingSession,
  AIHelpStudent,
  CommonConfusion,
} from './types';

export const MOCK_FACULTY_CLASSES: FacultyClass[] = [
  {
    id: 'cls-1',
    code: 'JAVA-3A',
    title: 'Advanced Java Microservices & Cloud Backend Architecture',
    department: 'Computer Science & Engineering',
    semester: 'Semester 6',
    enrolledStudents: 52,
    avgAttendanceRate: 94,
    avgBuilderScore: 784,
    nextSessionTime: 'Today at 2:00 PM',
    activeAssignmentsCount: 2,
  },
  {
    id: 'cls-2',
    code: 'AI-4B',
    title: 'PyTorch Deep Learning & LLM Fine-Tuning Sandbox',
    department: 'Artificial Intelligence & Machine Learning',
    semester: 'Semester 8',
    enrolledStudents: 44,
    avgAttendanceRate: 91,
    avgBuilderScore: 820,
    nextSessionTime: 'Tomorrow at 10:00 AM',
    activeAssignmentsCount: 1,
  },
  {
    id: 'cls-3',
    code: 'DS-2C',
    title: 'Distributed Data Pipelines & Kafka Real-Time Telemetry',
    department: 'Data Science',
    semester: 'Semester 4',
    enrolledStudents: 48,
    avgAttendanceRate: 88,
    avgBuilderScore: 712,
    nextSessionTime: 'Sep 28 at 11:30 AM',
    activeAssignmentsCount: 3,
  },
];

export const MOCK_STUDENTS: StudentRecord[] = [
  {
    id: 'st-01',
    name: 'Manutej Reddy',
    rollNumber: '22HT1A0501',
    department: 'CSE',
    email: 'manutej@hitam.edu',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
    builderScore: 890,
    attendanceRate: 98,
    assessmentAvg: 94,
    githubCommitsThisMonth: 142,
    projectsCompleted: 8,
    participationIndex: 96,
    riskStatus: 'Safe',
    weakTopics: ['Distributed Consensus'],
  },
  {
    id: 'st-02',
    name: 'Priya Sharma',
    rollNumber: '22HT1A0514',
    department: 'CSE',
    email: 'priya.s@hitam.edu',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    builderScore: 845,
    attendanceRate: 95,
    assessmentAvg: 91,
    githubCommitsThisMonth: 98,
    projectsCompleted: 6,
    participationIndex: 90,
    riskStatus: 'Safe',
    weakTopics: ['Spring Security OAuth2'],
  },
  {
    id: 'st-03',
    name: 'Karthik Raja',
    rollNumber: '22HT1A0532',
    department: 'CSE',
    email: 'karthik.r@hitam.edu',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150',
    builderScore: 640,
    attendanceRate: 72,
    assessmentAvg: 64,
    githubCommitsThisMonth: 18,
    projectsCompleted: 2,
    participationIndex: 58,
    riskStatus: 'Watchlist',
    riskReason: 'Low attendance in morning labs & missing Assignment 2 submission',
    weakTopics: ['Circular Dependencies', 'Custom Actuator Metrics', 'Spring Boot Autoconfig'],
  },
  {
    id: 'st-04',
    name: 'Aarav Patel',
    rollNumber: '22HT1A0545',
    department: 'AIML',
    email: 'aarav.p@hitam.edu',
    builderScore: 580,
    attendanceRate: 64,
    assessmentAvg: 58,
    githubCommitsThisMonth: 8,
    projectsCompleted: 1,
    participationIndex: 42,
    riskStatus: 'High Risk',
    riskReason: 'Failed 2 consecutive weekly micro-quizzes, attendance below 65%',
    weakTopics: ['Backpropagation Equations', 'Gradient Vanishing', 'PyTorch DataLoader'],
  },
  {
    id: 'st-05',
    name: 'Ananya Verma',
    rollNumber: '22HT1A0560',
    department: 'CSE',
    email: 'ananya.v@hitam.edu',
    builderScore: 815,
    attendanceRate: 96,
    assessmentAvg: 88,
    githubCommitsThisMonth: 76,
    projectsCompleted: 5,
    participationIndex: 88,
    riskStatus: 'Safe',
    weakTopics: ['Kafka Partitions'],
  },
];

export const MOCK_ASSIGNMENTS: AssignmentItem[] = [
  {
    id: 'asg-1',
    title: 'Lab 4: Resilient Microservices with Resilience4j & Circuit Breaker',
    classCode: 'JAVA-3A',
    dueDate: '2026-09-30',
    totalPoints: 100,
    submissionsCount: 42,
    totalStudents: 52,
    evaluatedCount: 28,
    status: 'Active',
    techStack: ['Spring Boot', 'Resilience4j', 'Eureka', 'Docker'],
    rubricCriteria: [
      { name: 'Circuit Breaker Implementation', maxPoints: 30, description: 'Fallbacks correctly trigger on 50% fault injection.' },
      { name: 'Fault Tolerant Telemetry', maxPoints: 30, description: 'Micrometer dashboard tracks circuit state.' },
      { name: 'Unit & Integration Tests', maxPoints: 20, description: 'MockWebServer tests fallback response.' },
      { name: 'Documentation & Docker Compose', maxPoints: 20, description: 'Clean README with setup commands.' },
    ],
  },
  {
    id: 'asg-2',
    title: 'Assignment 3: Fine-Tuning Llama-3 8B with LoRA & PEFT on Custom Dataset',
    classCode: 'AI-4B',
    dueDate: '2026-10-05',
    totalPoints: 100,
    submissionsCount: 30,
    totalStudents: 44,
    evaluatedCount: 12,
    status: 'Active',
    techStack: ['PyTorch', 'HuggingFace', 'PEFT', 'BitsAndBytes'],
    rubricCriteria: [
      { name: 'Data Pipeline & Tokenization', maxPoints: 25, description: 'Masking prompt tokens correctly.' },
      { name: 'LoRA Adapter Config', maxPoints: 35, description: 'Targeting q_proj, v_proj layers.' },
      { name: 'Evaluation Loss & Perplexity', maxPoints: 25, description: 'Validation perplexity < 4.5.' },
      { name: 'Gradients & Memory Log', maxPoints: 15, description: 'VRAM stays within 16GB limit.' },
    ],
  },
  {
    id: 'asg-3',
    title: 'Lab 2: Spring Security JWT Authentication & OAuth2 Social Login',
    classCode: 'JAVA-3A',
    dueDate: '2026-09-20',
    totalPoints: 100,
    submissionsCount: 52,
    totalStudents: 52,
    evaluatedCount: 52,
    status: 'Graded',
    techStack: ['Spring Security', 'JWT', 'PostgreSQL'],
    rubricCriteria: [
      { name: 'JWT Token Generation', maxPoints: 40, description: 'Correct signing algorithm and expiry.' },
      { name: 'Security Filter Chain', maxPoints: 40, description: 'Stateless session creation.' },
      { name: 'Error Handling', maxPoints: 20, description: 'Custom authentication entry point.' },
    ],
  },
];

export const MOCK_SUBMISSIONS: StudentSubmission[] = [
  {
    id: 'sub-1',
    assignmentId: 'asg-1',
    studentId: 'st-01',
    studentName: 'Manutej Reddy',
    submittedAt: '2026-09-25 18:40',
    status: 'Pending Evaluation',
    repoUrl: 'https://github.com/manutej/resilience4j-spring-demo',
    demoUrl: 'https://resilience.manutej.dev',
    notes: 'Implemented exponential backoff fallback with Redis caching.',
  },
  {
    id: 'sub-2',
    assignmentId: 'asg-1',
    studentId: 'st-02',
    studentName: 'Priya Sharma',
    submittedAt: '2026-09-25 21:15',
    status: 'Pending Evaluation',
    repoUrl: 'https://github.com/priyasharma/circuit-breaker-lab',
    notes: 'Added custom Prometheus counters for failed retry attempts.',
  },
  {
    id: 'sub-3',
    assignmentId: 'asg-1',
    studentId: 'st-03',
    studentName: 'Karthik Raja',
    submittedAt: '2026-09-26 11:02',
    status: 'Late',
    repoUrl: 'https://github.com/karthik/java-lab-4',
    notes: 'Submitted after fixing circular dependency in test config.',
  },
];

export const MOCK_UPCOMING_SESSIONS: UpcomingSession[] = [
  {
    id: 'sess-1',
    title: 'Spring Boot Microservices & Circuit Breakers',
    classCode: 'JAVA-3A',
    time: 'Today, 2:00 PM - 3:30 PM',
    type: 'Live Lecture',
    roomCode: 'JAVA-3A-2026',
  },
  {
    id: 'sess-2',
    title: 'Transformer Attention Mechanisms & QLoRA Hands-on',
    classCode: 'AI-4B',
    time: 'Today, 4:00 PM - 5:30 PM',
    type: 'Lab Session',
    roomCode: 'AI-LAB-4B',
  },
  {
    id: 'sess-3',
    title: 'Capstone Architecture 1-on-1 Office Hours',
    classCode: 'JAVA-3A',
    time: 'Tomorrow, 11:00 AM - 1:00 PM',
    type: 'Office Hours',
  },
];

export const MOCK_AI_HELP_STUDENTS: AIHelpStudent[] = [
  {
    studentId: 'st-04',
    name: 'Aarav Patel',
    classCode: 'AI-4B',
    builderScore: 580,
    primaryStruggle: 'Gradient vanishing equations & PyTorch Tensor shape mismatch',
    suggestedAction: 'Assign 15-min interactive tensor shape clinic & pair with Manutej Reddy for Lab 3.',
    riskLevel: 'High',
  },
  {
    studentId: 'st-03',
    name: 'Karthik Raja',
    classCode: 'JAVA-3A',
    builderScore: 640,
    primaryStruggle: 'Circular Bean Dependency Resolution & Spring Actuator custom endpoints',
    suggestedAction: 'Provide step-by-step video recap on @Lazy annotation and constructor injection.',
    riskLevel: 'Medium',
  },
];

export const MOCK_COMMON_CONFUSIONS: CommonConfusion[] = [
  {
    topic: 'Circular Bean Dependencies in Spring Boot',
    classCode: 'JAVA-3A',
    doubtCount: 18,
    affectedPct: 34,
    sampleQuestion: 'Why does Spring Boot throw BeanCurrentlyInCreationException when using constructor injection?',
    aiClarification: 'Constructor injection requires both instances to exist simultaneously. Breaking the cycle requires @Lazy or Setter Injection.',
  },
  {
    topic: 'LoRA Target Module Selection in HuggingFace PEFT',
    classCode: 'AI-4B',
    doubtCount: 14,
    affectedPct: 28,
    sampleQuestion: 'Should we target only q_proj and v_proj or all linear layers in Llama-3?',
    aiClarification: 'Targeting all linear layers yields higher accuracy with slightly more parameters, while q_proj + v_proj is most memory-efficient.',
  },
];
