import {
  FeedPost,
  BuilderTalent,
  MentorProfile,
  CommunityChallenge,
  CommunityEvent,
  ZeroReputationProfile,
} from './types';

export const MOCK_FEED_POSTS: FeedPost[] = [
  {
    id: 'post-1',
    authorName: 'Pratik Badiger',
    authorAvatar: 'https://github.com/pratikbadiger069.png',
    authorHandle: '@pratikbadiger069',
    authorRole: 'Lead Architect • SDE-1 Target',
    authorTrustScore: 98,
    category: 'Project Update',
    title: 'Shipped Dockerized Spring Boot Order Processing Microservice v1.4',
    content: 'Just deployed our high-throughput Redis caching gateway with atomic Lua script rate-limiting. Reduced API p99 response latency from 45ms to 8.2ms under 5k concurrent QPS load testing.',
    codeSnippet: {
      language: 'java',
      code: `@RestController\n@RequestMapping("/api/v1/orders")\npublic class OrderController {\n    private final OrderService orderService;\n\n    @PostMapping\n    public ResponseEntity<OrderDTO> createOrder(@Valid @RequestBody OrderRequest req) {\n        return ResponseEntity.ok(orderService.processOrder(req));\n    }\n}`,
    },
    projectLink: 'https://orders-api.skillbridge.dev',
    repositoryUrl: 'https://github.com/pratikbadiger069/spring-boot-order-service',
    appreciationsCount: 42,
    endorsementsCount: 18,
    reviewsCount: 6,
    userAppreciated: true,
    userEndorsed: false,
    reviews: [
      { id: 'rev-1', reviewerName: 'Dr. Evelyn Vance', text: 'Excellent domain isolation and stateless controller design. Code quality approved.', rating: 5, timestamp: '3 hours ago' },
      { id: 'rev-2', reviewerName: 'Rohan Verma', text: 'Verified the Redis Lua rate-limiting benchmark on our local docker-compose cluster.', rating: 5, timestamp: '1 hour ago' },
    ],
    timestamp: '2 hours ago',
  },
  {
    id: 'post-2',
    authorName: 'Ananya Sharma',
    authorAvatar: '',
    authorHandle: '@anasharma',
    authorRole: 'UI/UX Architect & Full-Stack',
    authorTrustScore: 95,
    category: 'Hackathon Win',
    title: '1st Place Winner at National AI Builder Sprint 2026! 🏆',
    content: 'Our team built an autonomous CRDT multiplayer canvas with WebSockets state synchronization. Thanks to everyone who reviewed our architecture docs during the 36-hour sprint!',
    projectLink: 'https://collaborative-canvas.dev',
    repositoryUrl: 'https://github.com/anasharma/crdt-canvas',
    appreciationsCount: 68,
    endorsementsCount: 29,
    reviewsCount: 12,
    userAppreciated: true,
    userEndorsed: true,
    reviews: [
      { id: 'rev-3', reviewerName: 'Prof. Rajesh Kumar', text: 'Outstanding presentation of CRDT conflict-free resolution algorithms.', rating: 5, timestamp: 'Yesterday' },
    ],
    timestamp: '1 day ago',
  },
  {
    id: 'post-3',
    authorName: 'Rohan Verma',
    authorAvatar: '',
    authorHandle: '@rohanv',
    authorRole: 'DevOps & Systems Lead',
    authorTrustScore: 92,
    category: 'Open Opportunity',
    title: 'Looking for 1 Backend Developer (Java / Spring Boot) for Open-Source Security Engine',
    content: 'Building a zero-downtime Kubernetes GitOps pipeline tool. Looking for a collaborator with basic Spring Boot or Go experience to co-author the CLI worker module.',
    repositoryUrl: 'https://github.com/rohanv/k8s-gitops-pipeline',
    appreciationsCount: 24,
    endorsementsCount: 8,
    reviewsCount: 4,
    reviews: [],
    timestamp: '2 days ago',
  },
];

export const MOCK_TALENT: BuilderTalent[] = [
  {
    id: 't-1',
    name: 'Pratik Badiger',
    avatar: 'https://github.com/pratikbadiger069.png',
    handle: '@pratikbadiger069',
    primaryRole: 'Lead Systems Architect',
    skills: ['Java 21', 'Spring Boot', 'TypeScript', 'Next.js', 'Docker', 'System Design'],
    reputationScore: 94,
    builderLevel: 'Elite Builder',
    availableForTeams: true,
    bio: 'Building high-throughput microservices & AI mentorship telemetry systems. 885 Builder Score.',
    matchedScore: 98,
  },
  {
    id: 't-2',
    name: 'Ananya Sharma',
    avatar: '',
    handle: '@anasharma',
    primaryRole: 'Frontend & UI/UX Specialist',
    skills: ['React', 'TypeScript', 'TailwindCSS', 'Figma', 'Framer Motion', 'WebSockets'],
    reputationScore: 91,
    builderLevel: 'Architect',
    availableForTeams: true,
    bio: 'Crafting responsive, glassmorphic interfaces and multiplayer CRDT canvases.',
    matchedScore: 94,
  },
  {
    id: 't-3',
    name: 'Rohan Verma',
    avatar: '',
    handle: '@rohanv',
    primaryRole: 'DevOps & Cloud Engineer',
    skills: ['Docker', 'Kubernetes', 'Terraform', 'AWS', 'Prometheus', 'CI/CD'],
    reputationScore: 88,
    builderLevel: 'DevOps Lead',
    availableForTeams: true,
    bio: 'Obsessed with multi-stage Docker builds, GitOps pipelines, and zero-downtime cloud deployments.',
    matchedScore: 90,
  },
  {
    id: 't-4',
    name: 'Kavya Nair',
    avatar: '',
    handle: '@kavyan',
    primaryRole: 'AI & Machine Learning Researcher',
    skills: ['Python', 'PyTorch', 'LangChain', 'FastAPI', 'pgvector', 'RAG Architecture'],
    reputationScore: 86,
    builderLevel: 'AI Creator',
    availableForTeams: false,
    bio: 'Researching hybrid RAG reranking algorithms & autonomous agentic workflows.',
    matchedScore: 85,
  },
];

export const MOCK_MENTORS: MentorProfile[] = [
  {
    id: 'm-1',
    name: 'Dr. Evelyn Vance',
    avatar: '',
    title: 'Senior Staff Systems Architect & HOD CSE',
    companyOrDept: 'HITAM Department of Computer Science',
    expertise: ['System Design', 'Enterprise Java', 'Distributed Systems', 'Career Roadmap'],
    rating: 4.9,
    totalSessions: 142,
    availableSlots: ['Mon 4:00 PM', 'Wed 2:00 PM', 'Fri 5:00 PM'],
    bio: '15+ years engineering scalable cloud systems. Faculty advisor for SkillBridge Mentorship Engine.',
  },
  {
    id: 'm-2',
    name: 'Prof. Rajesh Kumar',
    avatar: '',
    title: 'Associate Professor & DevOps Lead',
    companyOrDept: 'HITAM Innovation Center',
    expertise: ['Docker & Kubernetes', 'Cloud Infrastructure', 'CI/CD Automation'],
    rating: 4.8,
    totalSessions: 98,
    availableSlots: ['Tue 3:00 PM', 'Thu 4:30 PM'],
    bio: 'Specialist in cloud native deployment and container security.',
  },
];

export const MOCK_CHALLENGES: CommunityChallenge[] = [
  {
    id: 'c-1',
    title: 'Build a High-Throughput Redis Rate Limiter in 48 Hours',
    category: 'Build Sprint',
    description: 'Implement Token Bucket / Sliding Window algorithm using Redis atomic Lua scripts to withstand 10k QPS.',
    xpReward: 150,
    deadline: '3 Days Remaining',
    participantsCount: 42,
    sponsor: 'Razorpay Engineering',
    tags: ['System Design', 'Redis', 'Java / Node'],
  },
  {
    id: 'c-2',
    title: 'Zero-Downtime Docker Compose Local Stack Challenge',
    category: 'Weekly Challenge',
    description: 'Create multi-stage Dockerfiles reducing Java spring container size below 180MB.',
    xpReward: 100,
    deadline: '5 Days Remaining',
    participantsCount: 68,
    sponsor: 'SkillBridge OS',
    tags: ['Docker', 'DevOps'],
  },
  {
    id: 'c-3',
    title: 'Autonomous Multi-Agent Tool-Calling Hackathon',
    category: 'Hackathon',
    description: 'Build a 0-to-1 autonomous agent graph using LangGraph with human approval safety gates.',
    xpReward: 300,
    deadline: '10 Days Remaining',
    participantsCount: 110,
    sponsor: 'Google Cloud AI',
    tags: ['AI/ML', 'Python', 'LangGraph'],
  },
];

export const MOCK_EVENTS: CommunityEvent[] = [
  {
    id: 'e-1',
    title: 'Masterclass: Distributed System Design & Database Sharding',
    category: 'Tech Talk',
    hostName: 'Dr. Evelyn Vance',
    hostRole: 'Senior Staff Systems Architect',
    dateTime: 'Tomorrow at 5:00 PM IST',
    duration: '90 Mins',
    venueOrUrl: 'Auditorium 2 & SkillBridge Live Room',
    attendeesCount: 145,
    registered: true,
    description: 'Deep dive into database partitioning, master-replica replication, and consistent hashing algorithms.',
  },
  {
    id: 'e-2',
    title: '0-to-1 Founder Circle: Building Production SaaS Apps in College',
    category: 'Founder Sessions',
    hostName: 'Pratik Badiger',
    hostRole: 'Lead Architect, SkillBridge',
    dateTime: 'Friday at 4:00 PM IST',
    duration: '60 Mins',
    venueOrUrl: 'Innovation Lab 3',
    attendeesCount: 88,
    registered: false,
    description: 'Interactive session on validating product MVP, GitHub commit discipline, and pitching to industry recruiters.',
  },
];

export const MOCK_ZERO_REPUTATION: ZeroReputationProfile = {
  builderReputation: 94,
  mentorReputation: 88,
  communityImpact: 92,
  contributionScore: 1420,
  trustScore: 98,
  communityXp: 850,
  unlockedBadges: [
    { title: 'Top Code Reviewer', category: 'Community', date: 'Sept 20, 2026' },
    { title: 'Hackathon Champion', category: 'Build', date: 'Sept 15, 2026' },
    { title: 'Verified Mentor', category: 'Mentorship', date: 'Sept 10, 2026' },
  ],
  mentorshipHistory: [
    { sessionTitle: 'Spring Boot REST Architecture Code Review', menteeName: 'Ananya Sharma', date: 'Sept 24, 2026', rating: 5 },
    { sessionTitle: 'System Design Rate Limiter Guidance', menteeName: 'Rohan Verma', date: 'Sept 21, 2026', rating: 5 },
  ],
};
